version: '3.8'

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo-data:

services:
  mongo:
    image: mongo:7
    container_name: mongo
    networks:
      - microservices-net
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db